// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $contact from "./routes/contact.tsx";
import * as $events from "./routes/events.tsx";
import * as $gallery from "./routes/gallery.tsx";
import * as $index from "./routes/index.tsx";
import * as $members from "./routes/members.tsx";
import * as $MobileDrawer from "./islands/MobileDrawer.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/contact.tsx": $contact,
    "./routes/events.tsx": $events,
    "./routes/gallery.tsx": $gallery,
    "./routes/index.tsx": $index,
    "./routes/members.tsx": $members,
  },
  islands: {
    "./islands/MobileDrawer.tsx": $MobileDrawer,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
